nelmio_api_doc:
    areas:
        path_patterns: [ ^/api ]
    documentation:
        info:
            title: BileMo API
            description: This is an api for BileMo!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
       